import hara.lang.base.G;
import hara.lang.base.primitive.Murmur3;
import hara.lang.base.primitive.RapidHash;
import hara.lang.base.primitive.SipHash;
import hara.lang.data.Tuple;
import hara.lang.protocol.Constant;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;

/**
 * Dumps expected hash values from the Java runtime as the normative
 * hash-parity conformance corpus:
 *
 * <pre>
 * specs/01-lang/020-data-structures/draft/conformance/hash-parity.edn
 * </pre>
 *
 * <p>Regenerate (from the repo root, after {@code mvn -f java/pom.xml -Ptruffle package}):
 *
 * <pre>
 * javac -cp java/target/classes -d target/hashdump specs/scripts/hashdump/HashDump.java
 * java -cp target/hashdump:java/target/classes HashDump \
 *   > specs/01-lang/020-data-structures/draft/conformance/hash-parity.edn
 * </pre>
 *
 * <p>The output is deterministic (byte-identical across runs): every case is
 * derived from deterministic Java hash functions. Cases whose Java behaviour
 * is identity-based (Keyword.toString, Pointer, SYSTEM hash of collections)
 * are standardised on the documented display forms instead — see the spec
 * document for the deviation list.
 *
 * <p>Case format: {@code {:id :<hash>/<label> :hash :<hash> :kind :<kind>
 * :input <edn> :expect <java-long>}}. {@code :expect} is the decimal Java
 * long; 32-bit hashes (murmur3, system, canonical numbers) are sign-extended.
 */
public class HashDump {

  static StringBuilder OUT = new StringBuilder();
  static int COUNT = 0;

  // -------------------------------------------------------------------------
  // EDN emission
  // -------------------------------------------------------------------------

  /** EDN string literal escaping (matches the hara reader/display rules). */
  static String ednStr(String s) {
    StringBuilder sb = new StringBuilder("\"");
    for (int i = 0; i < s.length(); i++) {
      char c = s.charAt(i);
      switch (c) {
        case '"' -> sb.append("\\\"");
        case '\\' -> sb.append("\\\\");
        case '\n' -> sb.append("\\n");
        case '\r' -> sb.append("\\r");
        case '\t' -> sb.append("\\t");
        case '\b' -> sb.append("\\b");
        case '\f' -> sb.append("\\f");
        default -> {
          if (c < 0x20 || c == 0x7f) sb.append(String.format("\\u%04x", (int) c));
          else sb.append(c);
        }
      }
    }
    return sb.append('"').toString();
  }

  static void emit(String id, String hash, String kind, String inputEdn, long expect) {
    OUT.append("  {:id :").append(id)
        .append(" :hash :").append(hash)
        .append(" :kind :").append(kind)
        .append(" :input ").append(inputEdn)
        .append(" :expect ").append(expect)
        .append("}\n");
    COUNT++;
  }

  static void emitColl(String id, String hash, String structure, String inputEdn, long expect) {
    OUT.append("  {:id :").append(id)
        .append(" :hash :").append(hash)
        .append(" :kind :collection :structure :").append(structure)
        .append(" :input ").append(inputEdn)
        .append(" :expect ").append(expect)
        .append("}\n");
    COUNT++;
  }

  static void comment(String s) {
    OUT.append("  ; ").append(s).append('\n');
  }

  static String repeat(char c, int n) {
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i < n; i++) sb.append((char) ('A' + (i % 26)));
    return sb.toString();
  }

  // -------------------------------------------------------------------------
  // case groups
  // -------------------------------------------------------------------------

  static void dumpString(String label, String s) {
    byte[] utf8 = s.getBytes(StandardCharsets.UTF_8);
    String input = ednStr(s);
    emit("rapid/string-" + label, "rapid", "string", input, RapidHash.hash(utf8));
    emit("murmur3/string-" + label, "murmur3", "string", input, Murmur3.hashChars(s));
    emit("sip/string-" + label, "sip", "string", input, SipHash.hash(SipHash.HARA, utf8));
    emit("system/string-" + label, "system", "string", input, s.hashCode());
  }

  static void dumpDouble(String label, double d) {
    String input;
    if (Double.isNaN(d)) input = "##NaN";
    else if (d == Double.POSITIVE_INFINITY) input = "##Inf";
    else if (d == Double.NEGATIVE_INFINITY) input = "##-Inf";
    else input = Double.toString(d);
    emit("canonical/double-" + label, "system", "double", input,
        G.hashCalc(Constant.HashType.SYSTEM, d));
  }

  public static void main(String[] args) {
    OUT.append("""
        {:spec/version "0.1"
         :document/id :hara/data-structures-hash-parity-conformance
         :document/for :hara/data-structures
         :document/status :draft
         :note "Generated by specs/scripts/hashdump/HashDump.java against the Java runtime (see specs/01-lang/020-data-structures/draft/README.md). All values are Java long/int semantics: wrapping two's-complement arithmetic. :expect is the decimal Java long; 32-bit hashes (murmur3, system, canonical numbers) are sign-extended. :input is an EDN form per :kind - string: literal string; int/long: integer literal; double: float literal or ##NaN/##Inf/##-Inf; bigint/decimal: the BigDecimal-grammar string; bool/char/nil: literal; bytes: vector of signed byte values; seed: the ObjType name (hashSeed = \\"::\\" + name); keyword/symbol: literal form; collection: literal form (vector encoding for :queue and :tuple2, see :structure). KNOWN DIVERGENCE (excluded): Double.MIN_VALUE - Java Double.toString emits 4.9E-324 (hash 1844), Rust {} formatting picks 5e-324 (hash 479); both round-trip to the same double."
         :cases [
        """);

    // --- string cases ---
    dumpString("empty", "");
    dumpString("one", "a");
    dumpString("three", "abc");
    dumpString("four", "abcd");
    dumpString("five", "hello");
    dumpString("eight", "abcdefgh");
    dumpString("len15", repeat('A', 15));
    dumpString("len16", repeat('A', 16));
    dumpString("len17", repeat('A', 17));
    dumpString("len24", repeat('A', 24));
    dumpString("len31", repeat('A', 31));
    dumpString("len32", repeat('A', 32));
    dumpString("len33", repeat('A', 33));
    dumpString("len47", repeat('A', 47));
    dumpString("len48", repeat('A', 48));
    dumpString("len49", repeat('A', 49));
    dumpString("len63", repeat('A', 63));
    dumpString("len64", repeat('A', 64));
    dumpString("len96", repeat('A', 96));
    dumpString("len97", repeat('A', 97));
    dumpString("len144", repeat('A', 144));
    dumpString("bmp2", "héllo");
    dumpString("bmp3", "日本語");
    dumpString("surrogate", "😀");
    dumpString("mixed-unicode", "café ☕ 😀");
    dumpString("combining", "é");
    dumpString("pangram", "the quick brown fox jumps over the lazy dog");
    dumpString("escapes", "line\nbreak\ttab\"quote\"\\back");

    // --- murmur3 hashInt / hashLong ---
    long[] ints = {0, 1, -1, 42, Integer.MAX_VALUE, Integer.MIN_VALUE, 2147483647, -2147483648, 100};
    for (long v : ints) {
      emit("murmur3/int-" + v, "murmur3", "int", Long.toString(v), Murmur3.hashInt((int) v));
    }
    long[] longs = {0, 1, -1, 42, 4294967296L, Long.MAX_VALUE, Long.MIN_VALUE,
        1234567890123456789L, -1234567890123456789L};
    for (long v : longs) {
      emit("murmur3/long-" + v, "murmur3", "long", Long.toString(v), Murmur3.hashLong(v));
    }

    // --- canonical numbers via G.hashCalc(SYSTEM, x) == hashValue(x) ---
    // (plain numbers hash identically under every hash type: G.hashFn only
    // dispatches on IHash objects, everything else takes hashValue)
    long[] nums = {0, 1, -1, 42, 100, -7, 1000000, Long.MAX_VALUE, Long.MIN_VALUE,
        Integer.MAX_VALUE, 4611686018427387904L};
    for (long v : nums) {
      emit("canonical/long-" + v, "system", "long", Long.toString(v),
          G.hashCalc(Constant.HashType.SYSTEM, v));
    }
    comment("the Long path does NOT strip trailing zeros: hashValue(100L)=3100 vs hashValue(100.0)=29");
    dumpDouble("0.0", 0.0);
    dumpDouble("-0.0", -0.0);
    dumpDouble("1.0", 1.0);
    dumpDouble("-1.0", -1.0);
    dumpDouble("2.5", 2.5);
    dumpDouble("100.0", 100.0);
    dumpDouble("3.14159", 3.14159);
    dumpDouble("1e7", 1e7);
    dumpDouble("1.5e-7", 1.5e-7);
    dumpDouble("-13.75", -13.75);
    dumpDouble("0.1", 0.1);
    dumpDouble("1e22", 1e22);
    dumpDouble("max", Double.MAX_VALUE);
    dumpDouble("0.5", 0.5);
    dumpDouble("long-digits", 123456789.123456789);
    dumpDouble("NaN", Double.NaN);
    dumpDouble("Infinity", Double.POSITIVE_INFINITY);
    dumpDouble("-Infinity", Double.NEGATIVE_INFINITY);
    String[] bigints = {"1", "100", "-100", "123456789012345678901234567890",
        "-987654321098765432109876543210", "1000000000000000000000000", "0",
        "9223372036854775807", "9223372036854775808"};
    for (String v : bigints) {
      emit("canonical/bigint-" + v, "system", "bigint", ednStr(v),
          G.hashCalc(Constant.HashType.SYSTEM, new BigInteger(v)));
    }
    String[] decimals = {"1.0", "2.50", "1.50", "0.001", "-13.75", "123.4500", "1E+3",
        "0.0001", "100", "100.0", "3.141592653589793238462643383279", "-0.5", "0.0", "0E+7"};
    for (String v : decimals) {
      emit("canonical/decimal-" + v, "system", "decimal", ednStr(v),
          G.hashCalc(Constant.HashType.SYSTEM, new BigDecimal(v)));
    }

    // --- plain values: bool / char / bytes / nil via hashValue ---
    emit("canonical/bool-true", "system", "bool", "true",
        G.hashCalc(Constant.HashType.SYSTEM, true));
    emit("canonical/bool-false", "system", "bool", "false",
        G.hashCalc(Constant.HashType.SYSTEM, false));
    emit("canonical/char-a", "system", "char", "\\a",
        G.hashCalc(Constant.HashType.SYSTEM, 'a'));
    emit("canonical/char-A", "system", "char", "\\A",
        G.hashCalc(Constant.HashType.SYSTEM, 'A'));
    emit("canonical/char-newline", "system", "char", "\\newline",
        G.hashCalc(Constant.HashType.SYSTEM, '\n'));
    emit("canonical/char-e-acute", "system", "char", "\\u00E9",
        G.hashCalc(Constant.HashType.SYSTEM, 'é'));
    emit("canonical/bytes-basic", "system", "bytes", "[1 2 3 -1 127 -128]",
        G.hashCalc(Constant.HashType.SYSTEM, new byte[] {1, 2, 3, -1, 127, -128}));
    emit("canonical/nil", "system", "nil", "nil", G.hashRapid(null));

    // --- hash seeds: Java String.hashCode of "::" + ObjType name ---
    for (Constant.ObjType t : Constant.ObjType.values()) {
      emit("seed/" + t.name().toLowerCase().replace('_', '-'), "system", "seed",
          ednStr(t.name()), ("::" + t.name()).hashCode());
    }

    // --- string-type (keyword/symbol) hashes ---
    // NOTE(deviation): Java's IStringType.hashCalc uses toString(), and
    // Keyword does not override toString, so the raw Java hash is built on
    // Object.toString() identity garbage and is non-deterministic across JVM
    // runs. This corpus (and the spec) standardise on the display form:
    // keyword "::KEYWORD|:ns/name". Symbol inherits ObjPersistent.toString()
    // (class-name + "<" + display + ">") which IS deterministic and is
    // mirrored exactly: "::SYMBOL|hara.lang.data.Symbol<ns/name>".
    String[] kws = {":a", ":ns/name", ":a-b/c+d"};
    String[] kwLabels = {"a", "ns-name", "a-b-c+d"};
    for (int i = 0; i < kws.length; i++) {
      String hashed = "::KEYWORD|" + kws[i];
      emit("rapid/keyword-" + kwLabels[i], "rapid", "keyword", kws[i],
          RapidHash.hash(hashed.getBytes(StandardCharsets.UTF_8)));
      emit("murmur3/keyword-" + kwLabels[i], "murmur3", "keyword", kws[i],
          Murmur3.hashChars(hashed));
      emit("system/keyword-" + kwLabels[i], "system", "keyword", kws[i], hashed.hashCode());
      // IStringType.hashCalc(SIP) == -1
      emit("sip/keyword-" + kwLabels[i], "sip", "keyword", kws[i], -1);
    }
    String[] syms = {"a", "ns/name", "a-b/c+d"};
    String[] symLabels = {"a", "ns-name", "a-b-c+d"};
    for (int i = 0; i < syms.length; i++) {
      String hashed = "::SYMBOL|" + hara.lang.data.Symbol.create(syms[i]).toString();
      emit("rapid/symbol-" + symLabels[i], "rapid", "symbol", syms[i],
          RapidHash.hash(hashed.getBytes(StandardCharsets.UTF_8)));
      emit("murmur3/symbol-" + symLabels[i], "murmur3", "symbol", syms[i],
          Murmur3.hashChars(hashed));
      emit("system/symbol-" + symLabels[i], "system", "symbol", syms[i], hashed.hashCode());
      emit("sip/symbol-" + symLabels[i], "sip", "symbol", syms[i], -1);
    }

    // --- collections (actual Java data structures) ---
    emitColl("rapid/collection-vector-empty", "rapid", "vector", "[]",
        hara.lang.data.Vector.Standard.from(null).hashCalc(Constant.HashType.RAPID));
    emitColl("murmur3/collection-vector-empty", "murmur3", "vector", "[]",
        hara.lang.data.Vector.Standard.from(null).hashCalc(Constant.HashType.MURMUR3));

    var vInts = hara.lang.data.Vector.Standard.from(null, 1L, 2L, 3L);
    emitColl("rapid/collection-vector-ints", "rapid", "vector", "[1 2 3]",
        vInts.hashCalc(Constant.HashType.RAPID));
    emitColl("murmur3/collection-vector-ints", "murmur3", "vector", "[1 2 3]",
        vInts.hashCalc(Constant.HashType.MURMUR3));

    var vStrs = hara.lang.data.Vector.Standard.from(null, "a", "b", "c");
    emitColl("rapid/collection-vector-strs", "rapid", "vector", "[\"a\" \"b\" \"c\"]",
        vStrs.hashCalc(Constant.HashType.RAPID));
    emitColl("murmur3/collection-vector-strs", "murmur3", "vector", "[\"a\" \"b\" \"c\"]",
        vStrs.hashCalc(Constant.HashType.MURMUR3));

    var vMixed = hara.lang.data.Vector.Standard.from(null, 1L, "two", 3.0d, Boolean.TRUE, null);
    emitColl("rapid/collection-vector-mixed", "rapid", "vector", "[1 \"two\" 3.0 true nil]",
        vMixed.hashCalc(Constant.HashType.RAPID));
    emitColl("murmur3/collection-vector-mixed", "murmur3", "vector", "[1 \"two\" 3.0 true nil]",
        vMixed.hashCalc(Constant.HashType.MURMUR3));

    var vNested = hara.lang.data.Vector.Standard.from(null,
        hara.lang.data.Vector.Standard.from(null, 1L, 2L),
        hara.lang.data.Vector.Standard.from(null, 3L, 4L));
    emitColl("rapid/collection-vector-nested", "rapid", "vector", "[[1 2] [3 4]]",
        vNested.hashCalc(Constant.HashType.RAPID));
    emitColl("murmur3/collection-vector-nested", "murmur3", "vector", "[[1 2] [3 4]]",
        vNested.hashCalc(Constant.HashType.MURMUR3));

    var vCollMixed = hara.lang.data.Vector.Standard.from(null,
        1L,
        hara.lang.data.Vector.Standard.from(null, 2L, 3L),
        hara.lang.data.Map.Standard.from(null, "a", 1L),
        hara.lang.data.Set.Standard.from(null, 4L, 5L));
    emitColl("rapid/collection-vector-coll-mixed", "rapid", "vector",
        "[1 [2 3] {\"a\" 1} #{4 5}]", vCollMixed.hashCalc(Constant.HashType.RAPID));
    emitColl("murmur3/collection-vector-coll-mixed", "murmur3", "vector",
        "[1 [2 3] {\"a\" 1} #{4 5}]", vCollMixed.hashCalc(Constant.HashType.MURMUR3));

    Object[] big = new Object[40];
    for (int i = 0; i < 40; i++) big[i] = (long) i;
    var vBig = hara.lang.data.Vector.Standard.from(null, big);
    StringBuilder bigEdn = new StringBuilder("[");
    for (int i = 0; i < 40; i++) bigEdn.append(i == 0 ? "" : " ").append(i);
    bigEdn.append(']');
    emitColl("rapid/collection-vector-big40", "rapid", "vector", bigEdn.toString(),
        vBig.hashCalc(Constant.HashType.RAPID));
    emitColl("murmur3/collection-vector-big40", "murmur3", "vector", bigEdn.toString(),
        vBig.hashCalc(Constant.HashType.MURMUR3));

    var lInts = hara.lang.data.List.Standard.from(null, 1L, 2L, 3L);
    emitColl("rapid/collection-list-ints", "rapid", "list", "(1 2 3)",
        lInts.hashCalc(Constant.HashType.RAPID));
    emitColl("murmur3/collection-list-ints", "murmur3", "list", "(1 2 3)",
        lInts.hashCalc(Constant.HashType.MURMUR3));

    var qInts = hara.lang.data.Queue.Standard.from(null, 1L, 2L, 3L);
    emitColl("rapid/collection-queue-ints", "rapid", "queue", "[1 2 3]",
        qInts.hashCalc(Constant.HashType.RAPID));
    emitColl("murmur3/collection-queue-ints", "murmur3", "queue", "[1 2 3]",
        qInts.hashCalc(Constant.HashType.MURMUR3));

    var mEmpty = hara.lang.data.Map.Standard.from(null);
    emitColl("rapid/collection-map-empty", "rapid", "map", "{}",
        mEmpty.hashCalc(Constant.HashType.RAPID));

    var mStr = hara.lang.data.Map.Standard.from(null, "a", 1L, "b", 2L);
    emitColl("rapid/collection-map-str", "rapid", "map", "{\"a\" 1 \"b\" 2}",
        mStr.hashCalc(Constant.HashType.RAPID));
    emitColl("murmur3/collection-map-str", "murmur3", "map", "{\"a\" 1 \"b\" 2}",
        mStr.hashCalc(Constant.HashType.MURMUR3));

    var mMixed = hara.lang.data.Map.Standard.from(null,
        1L, "one", "two", 2L, 3.0d, hara.lang.data.Vector.Standard.from(null, 1L, 2L));
    emitColl("rapid/collection-map-mixed", "rapid", "map",
        "{1 \"one\" \"two\" 2 3.0 [1 2]}", mMixed.hashCalc(Constant.HashType.RAPID));
    emitColl("murmur3/collection-map-mixed", "murmur3", "map",
        "{1 \"one\" \"two\" 2 3.0 [1 2]}", mMixed.hashCalc(Constant.HashType.MURMUR3));

    var mNested = hara.lang.data.Map.Standard.from(null,
        "m", hara.lang.data.Map.Standard.from(null, "a", 1L),
        "v", hara.lang.data.Vector.Standard.from(null, 1L, 2L));
    emitColl("rapid/collection-map-nested", "rapid", "map",
        "{\"m\" {\"a\" 1} \"v\" [1 2]}", mNested.hashCalc(Constant.HashType.RAPID));
    emitColl("murmur3/collection-map-nested", "murmur3", "map",
        "{\"m\" {\"a\" 1} \"v\" [1 2]}", mNested.hashCalc(Constant.HashType.MURMUR3));

    var sInts = hara.lang.data.Set.Standard.from(null, 1L, 2L, 3L);
    emitColl("rapid/collection-set-ints", "rapid", "set", "#{1 2 3}",
        sInts.hashCalc(Constant.HashType.RAPID));
    emitColl("murmur3/collection-set-ints", "murmur3", "set", "#{1 2 3}",
        sInts.hashCalc(Constant.HashType.MURMUR3));

    var sStrs = hara.lang.data.Set.Standard.from(null, "a", "b");
    emitColl("rapid/collection-set-strs", "rapid", "set", "#{\"a\" \"b\"}",
        sStrs.hashCalc(Constant.HashType.RAPID));
    emitColl("murmur3/collection-set-strs", "murmur3", "set", "#{\"a\" \"b\"}",
        sStrs.hashCalc(Constant.HashType.MURMUR3));

    // --- map entry tuple (Tup2, seed "::SEQUENTIAL") ---
    var tup = new Tuple.Tup2.L<>(null, "a", 1L);
    emitColl("rapid/collection-tuple2-a-1", "rapid", "tuple2", "[\"a\" 1]",
        tup.hashCalc(Constant.HashType.RAPID));
    emitColl("murmur3/collection-tuple2-a-1", "murmur3", "tuple2", "[\"a\" 1]",
        tup.hashCalc(Constant.HashType.MURMUR3));

    OUT.append("]}\n");
    OUT.insert(0, "");
    System.out.print(OUT);
    System.err.println("cases: " + COUNT);
  }
}
